/**
 * Product BOLA coverage registry — uncheatable via matrix-completeness.test.ts.
 * EXPECTED_CELL_COUNT is a numeric literal; update ONLY when adding/removing cells
 * in the same PR. Never derive from PRODUCT_BOLA_CELLS.length.
 */
export const EXPECTED_CELL_COUNT = 72;

export type CoveragePostCondition =
  | "none"
  | "ownerDb_unchanged"
  | "row_absent_forbidden"
  | "no_success_audit";

export interface CoverageCell {
  id: string;
  method: string;
  pathPattern: string;
  actor: string;
  expectStatus: number;
  postCondition: CoveragePostCondition;
  testTitle: string;
  status: "covered" | "todo" | "gap" | "soft";
  suiteFile: string;
}

export const PRODUCT_BOLA_CELLS: CoverageCell[] = [
  // A. Tickets
  {
    id: "ticket.get.foreign.admin",
    method: "GET",
    pathPattern: "/tickets/:id",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "ticket.get.foreign.admin: foreign ORG_ADMIN GET returns 404",
    status: "covered",
    suiteFile: "product-bola/mutation-postconditions.test.ts",
  },
  {
    id: "ticket.patch.foreign.admin",
    method: "PATCH",
    pathPattern: "/tickets/:id",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "ownerDb_unchanged",
    testTitle: "ticket.patch.foreign.admin: foreign ORG_ADMIN PATCH returns 404 and ownerDb unchanged",
    status: "covered",
    suiteFile: "product-bola/mutation-postconditions.test.ts",
  },
  {
    id: "ticket.status.foreign.admin",
    method: "PATCH",
    pathPattern: "/tickets/:id/status",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "ownerDb_unchanged",
    testTitle: "ticket.status.foreign.admin: foreign ORG_ADMIN status PATCH returns 404 and ownerDb unchanged",
    status: "covered",
    suiteFile: "product-bola/mutation-postconditions.test.ts",
  },
  {
    id: "ticket.delete.foreign.admin",
    method: "DELETE",
    pathPattern: "/tickets/:id",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "row_absent_forbidden",
    testTitle: "ticket.delete.foreign.admin: foreign ORG_ADMIN DELETE returns 404 and row remains",
    status: "covered",
    suiteFile: "product-bola/mutation-postconditions.test.ts",
  },
  {
    id: "ticket.create.bodyOrgId.ignored",
    method: "POST",
    pathPattern: "/tickets",
    actor: "multi_org",
    expectStatus: 201,
    postCondition: "none",
    testTitle: "ticket.create.bodyOrgId.ignored: forged body orgId ignored; DB uses session org",
    status: "covered",
    suiteFile: "product-bola/mutation-postconditions.test.ts",
  },
  {
    id: "ticket.patch.assigneeId.foreignUser",
    method: "PATCH",
    pathPattern: "/tickets/:id",
    actor: "owner_mutator",
    expectStatus: 400,
    postCondition: "ownerDb_unchanged",
    testTitle: "ticket.patch.assigneeId.foreignUser: foreign assigneeId returns 400 invalid_assignee",
    status: "covered",
    suiteFile: "product-bola/assignee-mass-assignment.test.ts",
  },
  {
    id: "ticket.mutate.foreign.admin.noAudit",
    method: "PATCH",
    pathPattern: "/tickets/:id",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "no_success_audit",
    testTitle: "ticket.mutate.foreign.admin.noAudit: foreign PATCH 404 leaves no success audit",
    status: "covered",
    suiteFile: "product-bola/mutation-postconditions.test.ts",
  },

  // B. Comments
  {
    id: "ticket.comment.list.foreign.parent",
    method: "GET",
    pathPattern: "/tickets/:ticketId/comments",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "ticket.comment.list.foreign.parent: list comments under foreign ticket returns 404",
    status: "covered",
    suiteFile: "product-bola/nested-id-confusion.test.ts",
  },
  {
    id: "ticket.comment.create.foreign.parent",
    method: "POST",
    pathPattern: "/tickets/:ticketId/comments",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "ticket.comment.create.foreign.parent: create comment under foreign ticket returns 404",
    status: "covered",
    suiteFile: "product-bola/nested-id-confusion.test.ts",
  },
  {
    id: "ticket.comment.patch.child.crossOrg",
    method: "PATCH",
    pathPattern: "/tickets/:ticketId/comments/:commentId",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "ownerDb_unchanged",
    testTitle: "ticket.comment.patch.child.crossOrg: PATCH foreign commentId returns 404 and ownerDb unchanged",
    status: "covered",
    suiteFile: "product-bola/nested-id-confusion.test.ts",
  },
  {
    id: "ticket.comment.delete.child.crossOrg",
    method: "DELETE",
    pathPattern: "/tickets/:ticketId/comments/:commentId",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "row_absent_forbidden",
    testTitle: "ticket.comment.delete.child.crossOrg: DELETE foreign commentId returns 404 and row remains",
    status: "covered",
    suiteFile: "product-bola/nested-id-confusion.test.ts",
  },
  {
    id: "ticket.comment.patch.sameOrg.siblingParent",
    method: "PATCH",
    pathPattern: "/tickets/:ticketId/comments/:commentId",
    actor: "same_org_admin",
    expectStatus: 404,
    postCondition: "ownerDb_unchanged",
    testTitle: "ticket.comment.patch.sameOrg.siblingParent: comment under wrong sibling ticket path returns 404",
    status: "covered",
    suiteFile: "product-bola/nested-id-confusion.test.ts",
  },
  {
    id: "ticket.comment.delete.sameOrg.siblingParent",
    method: "DELETE",
    pathPattern: "/tickets/:ticketId/comments/:commentId",
    actor: "same_org_admin",
    expectStatus: 404,
    postCondition: "row_absent_forbidden",
    testTitle: "ticket.comment.delete.sameOrg.siblingParent: delete comment under wrong sibling ticket path returns 404",
    status: "covered",
    suiteFile: "product-bola/nested-id-confusion.test.ts",
  },

  // C. Attachments
  {
    id: "ticket.attach.list.foreign",
    method: "GET",
    pathPattern: "/tickets/:ticketId/attachments",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "ticket.attach.list.foreign: list attachments under foreign ticket returns 404",
    status: "covered",
    suiteFile: "product-bola/nested-id-confusion.test.ts",
  },
  {
    id: "ticket.attach.upload.foreign",
    method: "POST",
    pathPattern: "/tickets/:ticketId/attachments",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "ticket.attach.upload.foreign: upload under foreign ticket returns 404",
    status: "covered",
    suiteFile: "product-bola/nested-id-confusion.test.ts",
  },
  {
    id: "ticket.attach.meta.foreign",
    method: "GET",
    pathPattern: "/tickets/:ticketId/attachments/:attachmentId",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "ticket.attach.meta.foreign: meta under foreign ticket returns 404",
    status: "covered",
    suiteFile: "product-bola/nested-id-confusion.test.ts",
  },
  {
    id: "ticket.attach.download.foreign",
    method: "GET",
    pathPattern: "/tickets/:ticketId/attachments/:attachmentId/download",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "ticket.attach.download.foreign: download under foreign ticket returns 404",
    status: "covered",
    suiteFile: "product-bola/nested-id-confusion.test.ts",
  },
  {
    id: "ticket.attach.delete.foreign",
    method: "DELETE",
    pathPattern: "/tickets/:ticketId/attachments/:attachmentId",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "row_absent_forbidden",
    testTitle: "ticket.attach.delete.foreign: DELETE foreign attachment returns 404 and row remains",
    status: "covered",
    suiteFile: "product-bola/nested-id-confusion.test.ts",
  },
  {
    id: "ticket.attach.meta.sameOrg.siblingParent",
    method: "GET",
    pathPattern: "/tickets/:ticketId/attachments/:attachmentId",
    actor: "same_org_admin",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "ticket.attach.meta.sameOrg.siblingParent: meta with wrong parent ticketId returns 404",
    status: "covered",
    suiteFile: "product-bola/nested-id-confusion.test.ts",
  },
  {
    id: "ticket.attach.download.sameOrg.siblingParent",
    method: "GET",
    pathPattern: "/tickets/:ticketId/attachments/:attachmentId/download",
    actor: "same_org_admin",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "ticket.attach.download.sameOrg.siblingParent: download with wrong parent ticketId returns 404",
    status: "covered",
    suiteFile: "product-bola/nested-id-confusion.test.ts",
  },
  {
    id: "ticket.attach.delete.sameOrg.siblingParent",
    method: "DELETE",
    pathPattern: "/tickets/:ticketId/attachments/:attachmentId",
    actor: "same_org_admin",
    expectStatus: 404,
    postCondition: "row_absent_forbidden",
    testTitle: "ticket.attach.delete.sameOrg.siblingParent: delete with wrong parent ticketId returns 404",
    status: "covered",
    suiteFile: "product-bola/nested-id-confusion.test.ts",
  },
  {
    id: "ticket.attach.meta.share.sibling",
    method: "GET",
    pathPattern: "/tickets/:ticketId/attachments/:attachmentId",
    actor: "share_holder",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "ticket.attach.meta.share.sibling: shared ticketId + sibling attachmentId returns 404",
    status: "covered",
    suiteFile: "product-bola/nested-id-confusion.test.ts",
  },
  {
    id: "ticket.attach.download.share.sibling",
    method: "GET",
    pathPattern: "/tickets/:ticketId/attachments/:attachmentId/download",
    actor: "share_holder",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "ticket.attach.download.share.sibling: shared ticketId + sibling attachment download returns 404",
    status: "covered",
    suiteFile: "product-bola/nested-id-confusion.test.ts",
  },
  {
    id: "ticket.attach.flag.sharedDownloadAllowed",
    method: "GET",
    pathPattern: "/tickets/:ticketId/attachments/:attachmentId/download",
    actor: "share_holder",
    expectStatus: 200,
    postCondition: "none",
    testTitle: "ticket.attach.flag.sharedDownloadAllowed: attachmentsEnabled=false still allows shared download",
    status: "covered",
    suiteFile: "product-bola/nested-id-confusion.test.ts",
  },
  {
    id: "ticket.attach.flag.sharedUploadBlocked",
    method: "POST",
    pathPattern: "/tickets/:ticketId/attachments",
    actor: "share_holder",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "ticket.attach.flag.sharedUploadBlocked: attachmentsEnabled=false shared upload returns 404",
    status: "covered",
    suiteFile: "product-bola/nested-id-confusion.test.ts",
  },
  {
    id: "ticket.attach.afterMembershipDrop",
    method: "GET",
    pathPattern: "/tickets/:ticketId/attachments",
    actor: "share_holder_after_drop",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "ticket.attach.afterMembershipDrop: after Eve membership deleted list/meta/download return 404",
    status: "covered",
    suiteFile: "product-bola/membership-drop-nested.test.ts",
  },

  // D. PRs
  {
    id: "pr.get.foreign.admin",
    method: "GET",
    pathPattern: "/prs/:id",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "pr.get.foreign.admin: foreign ORG_ADMIN GET returns 404",
    status: "covered",
    suiteFile: "product-bola/pr-nested-bola.test.ts",
  },
  {
    id: "pr.patch.foreign.admin",
    method: "PATCH",
    pathPattern: "/prs/:id",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "ownerDb_unchanged",
    testTitle: "pr.patch.foreign.admin: foreign ORG_ADMIN PATCH returns 404 and ownerDb unchanged",
    status: "covered",
    suiteFile: "product-bola/pr-nested-bola.test.ts",
  },
  {
    id: "pr.review.foreign.admin",
    method: "POST",
    pathPattern: "/prs/:id/reviews",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "ownerDb_unchanged",
    testTitle: "pr.review.foreign.admin: foreign ORG_ADMIN review returns 404 and ownerDb unchanged",
    status: "covered",
    suiteFile: "product-bola/pr-nested-bola.test.ts",
  },
  {
    id: "pr.transition.foreign.admin",
    method: "POST",
    pathPattern: "/prs/:id/transition",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "ownerDb_unchanged",
    testTitle: "pr.transition.foreign.admin: foreign ORG_ADMIN transition returns 404 and ownerDb unchanged",
    status: "covered",
    suiteFile: "product-bola/pr-nested-bola.test.ts",
  },
  {
    id: "pr.versions.foreign.admin",
    method: "GET",
    pathPattern: "/prs/:id/versions",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "pr.versions.foreign.admin: foreign ORG_ADMIN GET /versions returns 404",
    status: "covered",
    suiteFile: "product-bola/pr-nested-bola.test.ts",
  },
  {
    id: "pr.diff.foreign.admin",
    method: "GET",
    pathPattern: "/prs/:id/versions/:n/diff",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "pr.diff.foreign.admin: foreign ORG_ADMIN GET /diff returns 404",
    status: "covered",
    suiteFile: "product-bola/pr-nested-bola.test.ts",
  },
  {
    id: "pr.versions.share.holder",
    method: "GET",
    pathPattern: "/prs/:id/versions",
    actor: "share_holder",
    expectStatus: 200,
    postCondition: "none",
    testTitle: "pr.versions.share.holder: Eve GET /prs/:id/versions returns 200",
    status: "covered",
    suiteFile: "product-bola/pr-nested-bola.test.ts",
  },
  {
    id: "pr.diff.share.holder",
    method: "GET",
    pathPattern: "/prs/:id/versions/:n/diff",
    actor: "share_holder",
    expectStatus: 200,
    postCondition: "none",
    testTitle: "pr.diff.share.holder: Eve GET /prs/:id/versions/:n/diff returns 200",
    status: "covered",
    suiteFile: "product-bola/pr-nested-bola.test.ts",
  },
  {
    id: "pr.versions.share.sibling",
    method: "GET",
    pathPattern: "/prs/:siblingId/versions",
    actor: "share_holder",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "pr.versions.share.sibling: Eve GET sibling /versions returns 404",
    status: "covered",
    suiteFile: "product-bola/pr-nested-bola.test.ts",
  },
  {
    id: "pr.mutator.eve.transition",
    method: "POST",
    pathPattern: "/prs/:id/transition",
    actor: "share_holder_support_agent",
    expectStatus: 403,
    postCondition: "ownerDb_unchanged",
    testTitle: "pr.mutator.eve.transition: Eve POST transition returns 403 and ownerDb unchanged",
    status: "covered",
    suiteFile: "product-bola/pr-nested-bola.test.ts",
  },
  {
    id: "pr.mutator.eve.review",
    method: "POST",
    pathPattern: "/prs/:id/reviews",
    actor: "share_holder_support_agent",
    expectStatus: 403,
    postCondition: "ownerDb_unchanged",
    testTitle: "pr.mutator.eve.review: Eve POST reviews returns 403 and ownerDb unchanged",
    status: "covered",
    suiteFile: "product-bola/pr-nested-bola.test.ts",
  },
  {
    id: "pr.mutator.eve.patch",
    method: "PATCH",
    pathPattern: "/prs/:id",
    actor: "share_holder_support_agent",
    expectStatus: 403,
    postCondition: "ownerDb_unchanged",
    testTitle: "pr.mutator.eve.patch: Eve PATCH returns 403 and ownerDb unchanged",
    status: "covered",
    suiteFile: "product-bola/pr-nested-bola.test.ts",
  },
  {
    id: "pr.delete.absent",
    method: "DELETE",
    pathPattern: "/prs/:id",
    actor: "org_admin",
    expectStatus: 404,
    postCondition: "row_absent_forbidden",
    testTitle: "pr.delete.absent: DELETE /prs/:id returns 404 and row remains",
    status: "covered",
    suiteFile: "product-bola/http-method-absence.test.ts",
  },
  {
    id: "pr.create.bodyOrgId.ignored",
    method: "POST",
    pathPattern: "/prs",
    actor: "org_admin",
    expectStatus: 201,
    postCondition: "none",
    testTitle: "pr.create.bodyOrgId.ignored: forged body orgId ignored; DB uses session org",
    status: "covered",
    suiteFile: "product-bola/pr-share-bola-matrix.test.ts",
  },
  {
    id: "pr.list.eve.noOwnerOrgWiden",
    method: "GET",
    pathPattern: "/prs",
    actor: "share_holder_support_agent",
    expectStatus: 403,
    postCondition: "none",
    testTitle: "pr.list.eve.noOwnerOrgWiden: Eve GET /prs returns 403",
    status: "covered",
    suiteFile: "product-bola/pr-share-bola-matrix.test.ts",
  },
  {
    id: "pr.comment.list.foreign.noShare",
    method: "GET",
    pathPattern: "/prs/:id/comments",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "pr.comment.list.foreign.noShare: list comments on foreign PR returns 404",
    status: "covered",
    suiteFile: "product-bola/pr-share-bola-matrix.test.ts",
  },
  {
    id: "pr.comment.create.foreign.noShare",
    method: "POST",
    pathPattern: "/prs/:id/comments",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "pr.comment.create.foreign.noShare: create comment on foreign PR returns 404",
    status: "covered",
    suiteFile: "product-bola/pr-share-bola-matrix.test.ts",
  },
  {
    id: "pr.comment.share.sibling",
    method: "GET",
    pathPattern: "/prs/:siblingId/comments",
    actor: "share_holder",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "pr.comment.share.sibling: Eve comments on unshared sibling PR returns 404",
    status: "covered",
    suiteFile: "product-bola/pr-share-bola-matrix.test.ts",
  },
  {
    id: "pr.comment.afterMembershipDrop",
    method: "GET",
    pathPattern: "/prs/:id/comments",
    actor: "share_holder_after_drop",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "pr.comment.afterMembershipDrop: after Eve membership deleted PR comments return 404",
    status: "covered",
    suiteFile: "product-bola/membership-drop-nested.test.ts",
  },

  // E. Shares / connections
  {
    id: "share.create.foreign.ticket",
    method: "POST",
    pathPattern: "/tickets/:ticketId/shares",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "share.create.foreign.ticket: POST share under foreign ticket returns 404",
    status: "covered",
    suiteFile: "product-bola/share-revoke-access.test.ts",
  },
  {
    id: "share.create.foreign.pr",
    method: "POST",
    pathPattern: "/prs/:prId/shares",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "share.create.foreign.pr: POST share under foreign PR returns 404",
    status: "covered",
    suiteFile: "product-bola/share-revoke-access.test.ts",
  },
  {
    id: "share.delete.outsider",
    method: "DELETE",
    pathPattern: "/shares/:shareId",
    actor: "unrelated_user",
    expectStatus: 404,
    postCondition: "ownerDb_unchanged",
    testTitle: "share.delete.outsider: unrelated DELETE shareId returns 404 and grant stays ACTIVE",
    status: "covered",
    suiteFile: "product-bola/share-revoke-access.test.ts",
  },
  {
    id: "share.delete.grantee.self",
    method: "DELETE",
    pathPattern: "/shares/:shareId",
    actor: "grantee_self",
    expectStatus: 200,
    postCondition: "none",
    testTitle: "share.delete.grantee.self: grantee deletes own inbound share → REVOKED",
    status: "covered",
    suiteFile: "product-bola/share-revoke-access.test.ts",
  },
  {
    id: "share.delete.granteeAdmin",
    method: "DELETE",
    pathPattern: "/shares/:shareId",
    actor: "grantee_org_admin",
    expectStatus: 200,
    postCondition: "none",
    testTitle: "share.delete.granteeAdmin: grantee ORG_ADMIN deletes peer share → REVOKED",
    status: "covered",
    suiteFile: "product-bola/share-revoke-access.test.ts",
  },
  {
    id: "share.revoke.then.get",
    method: "GET",
    pathPattern: "/tickets/:id",
    actor: "share_holder_after_revoke",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "share.revoke.then.get: after owner revoke grantee GET resource returns 404",
    status: "covered",
    suiteFile: "product-bola/share-revoke-access.test.ts",
  },
  {
    id: "share.inbound.afterRevoke",
    method: "GET",
    pathPattern: "/shares/inbound",
    actor: "share_holder_after_revoke",
    expectStatus: 200,
    postCondition: "none",
    testTitle: "share.inbound.afterRevoke: GET /shares/inbound excludes revoked share id",
    status: "covered",
    suiteFile: "product-bola/share-revoke-access.test.ts",
  },
  {
    id: "share.sharedInbox.afterRevoke",
    method: "GET",
    pathPattern: "/shared/tickets",
    actor: "share_holder_after_revoke",
    expectStatus: 200,
    postCondition: "none",
    testTitle: "share.sharedInbox.afterRevoke: GET /shared/tickets excludes revoked resource",
    status: "covered",
    suiteFile: "product-bola/share-revoke-access.test.ts",
  },
  {
    id: "connection.revoke.then.get",
    method: "GET",
    pathPattern: "/tickets/:id",
    actor: "share_holder_after_connection_revoke",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "connection.revoke.then.get: after connection revoke grantee GET returns 404",
    status: "covered",
    suiteFile: "product-bola/share-revoke-access.test.ts",
  },
  {
    id: "connection.revoked.grantStillActive",
    method: "GET",
    pathPattern: "/tickets/:id",
    actor: "share_holder",
    expectStatus: 404,
    postCondition: "ownerDb_unchanged",
    testTitle: "connection.revoked.grantStillActive: ACTIVE grant + REVOKED connection → GET 404",
    status: "covered",
    suiteFile: "product-bola/share-revoke-access.test.ts",
  },
  {
    id: "platform.forceRevoke.then.get",
    method: "GET",
    pathPattern: "/tickets/:id",
    actor: "share_holder_after_force_revoke",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "platform.forceRevoke.then.get: after platform force-revoke Eve GET returns 404",
    status: "covered",
    suiteFile: "product-bola/share-revoke-access.test.ts",
  },
  {
    id: "connection.recipients.foreignConnectionId",
    method: "GET",
    pathPattern: "/connections/:id/recipients",
    actor: "foreign_org_admin",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "connection.recipients.foreignConnectionId: GET recipients for foreign connectionId returns 404",
    status: "covered",
    suiteFile: "product-bola/share-revoke-access.test.ts",
  },
  {
    id: "share.pr.revoke.reshare",
    method: "POST",
    pathPattern: "/prs/:prId/shares",
    actor: "owner_admin",
    expectStatus: 201,
    postCondition: "none",
    testTitle: "share.pr.revoke.reshare: revoke then reshare leaves one ACTIVE plus prior REVOKED",
    status: "covered",
    suiteFile: "product-bola/pr-share-bola-matrix.test.ts",
  },
  {
    id: "share.pr.sameOrg.400",
    method: "POST",
    pathPattern: "/prs/:prId/shares",
    actor: "owner_admin",
    expectStatus: 400,
    postCondition: "none",
    testTitle: "share.pr.sameOrg.400: same-org PR share returns 400",
    status: "covered",
    suiteFile: "product-bola/pr-share-bola-matrix.test.ts",
  },
  {
    id: "share.pr.membershipDrop",
    method: "GET",
    pathPattern: "/prs/:id",
    actor: "share_holder_after_drop",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "share.pr.membershipDrop: remove membership → shared PR GET returns 404",
    status: "covered",
    suiteFile: "product-bola/membership-drop-nested.test.ts",
  },

  // F. Audit / settings / auth
  {
    id: "audit.list.scoped",
    method: "GET",
    pathPattern: "/audit",
    actor: "org_admin",
    expectStatus: 200,
    postCondition: "none",
    testTitle: "audit.list.scoped: list returns only active-org audit rows",
    status: "covered",
    suiteFile: "product-bola/http-method-absence.test.ts",
  },
  {
    id: "audit.orgIdFilter.forbidden",
    method: "GET",
    pathPattern: "/audit",
    actor: "org_admin",
    expectStatus: 403,
    postCondition: "none",
    testTitle: "audit.orgIdFilter.forbidden: foreign orgId query filter returns 403",
    status: "covered",
    suiteFile: "product-bola/http-method-absence.test.ts",
  },
  {
    id: "audit.export.scoped",
    method: "GET",
    pathPattern: "/audit/export",
    actor: "org_admin",
    expectStatus: 200,
    postCondition: "none",
    testTitle: "audit.export.scoped: export CSV scoped to active org only",
    status: "covered",
    suiteFile: "product-bola/http-method-absence.test.ts",
  },
  {
    id: "audit.http.put.absent",
    method: "PUT",
    pathPattern: "/audit",
    actor: "org_admin",
    expectStatus: 404,
    postCondition: "none",
    testTitle: "audit.http.put.absent: PUT /audit returns 404",
    status: "covered",
    suiteFile: "product-bola/http-method-absence.test.ts",
  },
  {
    id: "audit.http.patch.absent",
    method: "PATCH",
    pathPattern: "/audit/:id",
    actor: "org_admin",
    expectStatus: 404,
    postCondition: "ownerDb_unchanged",
    testTitle: "audit.http.patch.absent: PATCH /audit/:id returns 404 and row unchanged",
    status: "covered",
    suiteFile: "product-bola/http-method-absence.test.ts",
  },
  {
    id: "audit.http.delete.absent",
    method: "DELETE",
    pathPattern: "/audit/:id",
    actor: "org_admin",
    expectStatus: 404,
    postCondition: "ownerDb_unchanged",
    testTitle: "audit.http.delete.absent: DELETE /audit/:id returns 404 and row unchanged",
    status: "covered",
    suiteFile: "product-bola/http-method-absence.test.ts",
  },
  {
    id: "settings.patch.sessionOnly",
    method: "PATCH",
    pathPattern: "/org/settings",
    actor: "org_admin",
    expectStatus: 200,
    postCondition: "ownerDb_unchanged",
    testTitle: "settings.patch.sessionOnly: body orgId ignored; foreign org settings unchanged",
    status: "covered",
    suiteFile: "product-bola/http-method-absence.test.ts",
  },
  {
    id: "settings.http.delete.absent",
    method: "DELETE",
    pathPattern: "/org/settings",
    actor: "org_admin",
    expectStatus: 404,
    postCondition: "ownerDb_unchanged",
    testTitle: "settings.http.delete.absent: DELETE /org/settings returns 404 and settings unchanged",
    status: "covered",
    suiteFile: "product-bola/http-method-absence.test.ts",
  },
  {
    id: "auth.switchOrg.foreign",
    method: "POST",
    pathPattern: "/auth/switch-org",
    actor: "org_admin",
    expectStatus: 403,
    postCondition: "none",
    testTitle: "auth.switchOrg.foreign: switch-org to foreign org returns 403; session unchanged",
    status: "covered",
    suiteFile: "product-bola/http-method-absence.test.ts",
  },
  {
    id: "auth.queryOrgId.ignored",
    method: "GET",
    pathPattern: "/rbac/org",
    actor: "org_admin",
    expectStatus: 200,
    postCondition: "none",
    testTitle: "auth.queryOrgId.ignored: query orgId ignored; active org unchanged",
    status: "covered",
    suiteFile: "product-bola/http-method-absence.test.ts",
  },
  {
    id: "auth.bearerForged.cookieSessionWins",
    method: "GET",
    pathPattern: "/rbac/org",
    actor: "org_admin",
    expectStatus: 200,
    postCondition: "none",
    testTitle: "auth.bearerForged.cookieSessionWins: forged Bearer ignored; cookie session org wins",
    status: "covered",
    suiteFile: "product-bola/http-method-absence.test.ts",
  },
  {
    id: "platformAdmin.noActiveOrg.ticketGet",
    method: "GET",
    pathPattern: "/tickets/:id",
    actor: "platform_admin_no_membership",
    expectStatus: 403,
    postCondition: "none",
    testTitle: "platformAdmin.noActiveOrg.ticketGet: platform admin without membership gets 403 no_active_org",
    status: "covered",
    suiteFile: "product-bola/http-method-absence.test.ts",
  },
];
